<a href="https://colab.research.google.com/github/yauzaa/datalearn/blob/main/Numpy%20%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%8B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x = [2, 4, 5]
y = [10, 4, 2]

x + y

[2, 4, 5, 10, 4, 2]

In [4]:
x_np = np.array(x)
y_np = np.array(y)

In [5]:
print(x_np + y_np)
print(x_np * 2)
print(x_np ** 9)

[12  8  7]
[ 4  8 10]
[    512  262144 1953125]


In [6]:
z = ['cat', 1, 8.2]

print(z)
z_np = np.array(z) #str most powerfull
print(z_np[2])

['cat', 1, 8.2]
8.2


In [20]:
age = np.array([18, 20, 43, 23, 14, 52, 12])

In [21]:
age < 18

array([False, False, False, False,  True, False,  True])

In [22]:
(age < 18) | (age >= 35)

array([False, False,  True, False,  True,  True,  True])

In [23]:
age[(age < 18) | (age >= 35)]

array([43, 14, 52, 12])

In [30]:
a = np.array([[2, 5, 6], [8, 10, 4]])
a

array([[ 2,  5,  6],
       [ 8, 10,  4]])

In [33]:
print(a.shape)
print(a.ndim) # сколько измерний
print(a.size) # сколько значений

(2, 3)
2
6


In [36]:
print(a[1][0])
print(a[1,0])
print(a[:,0]) # все ряды 0 колонка

8
8
[2 8]


In [37]:
import time

In [40]:
# задаем размер наших списков
size = 1000000

# объявляем списки
list1 = range(size)
list2 = range(size)

# Запоминаем временную метку
initial_time = time.time()

# перемножаем элементы списков
result_list = [(a * b) for a, b in zip(list1, list2)]
list_time = time.time() - initial_time

# смотрим, сколько времени это заняло
print("Время: {} сек".format(list_time))

Время: 0.14600872993469238 сек


In [43]:
# то же самое в numpy

array1 = np.arange(size)
array2 = np.arange(size)

initial_time = time.time()

result_array = array1 * array2

array_time = time.time() - initial_time

print("Время: {} сек".format(array_time))
print(f"Во сколько раз? {round(list_time / array_time)} раз")

Время: 0.002497434616088867 сек
Во сколько раз? 58 раз
